# Copyright Contributors to the Open Cluster Management project
dist: xenial
sudo: required
language: generic

   
os:
  - linux

services:
  - docker

stages:
  - auto

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

jobs:
  include:
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = push AND branch =~ /^master$/
      script: 
        - git clone --single-branch --branch master https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh management-ingress-chart