# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Copyright Contributors to the Open Cluster Management project
---

{{ if (lookup "v1" "Secret" .Release.Namespace "byo-ingress-tls-secret") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.console_route.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
  annotations:
    route.openshift.io/termination: "reencrypt"
    route.openshift.io/insecureEdgeTerminationPolicy: "Redirect"
spec:
  rules:
  - host: {{ template "management-ingress.consoleRouteHost" . }}
    http:
      paths:
      - pathType: "ImplementationSpecific"
        backend:
          service:
            name: {{ .Values.service_name }}
            port:
              name: https
  tls:
  - hosts:
    - {{ template "management-ingress.consoleRouteHost" . }}
    secretName: byo-ingress-tls-secret
{{ else }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.console_route.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  host: {{ template "management-ingress.consoleRouteHost" . }}
  subdomain: {{ .Values.console_route.subdomain }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: {{ .Values.service_name }}
    weight: 100
  port:
    targetPort: https
  wildcardPolicy: None
status:
  ingress: []
{{ end }}