# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  __metadata:
    name: "image setting"
    label: "image setting"
    description: "set image repository, tag and pullPolicy"
  repository:
    __metadata:
      name: "image repository setting"
      label: "image repository setting"
      description: "set image repository, default is ibmcom/icp-management-ingress"
  tag:
    __metadata:
      name: "image tag setting"
      label: "image tag setting"
      description: "set image tag version"
  pullPolicy:
    __metadata:
      name: "image pullPolicy setting"
      label: "image pullPolicy setting"
      description: "set image pullPolicy, default is IfNotPresent"

resources:
  __metadata:
    name: "resources requests"
    label: "resources requests"
    description: "resources requests for cpu and memory"
  requests:
    cpu:
      __metadata:
        name: "cpu resources requests"
        label: "cpu resources requests"
        description: "resources requests for cpu"
    memory:
      __metadata:
        name: "memory resources requests"
        label: "memory resources requests"
        description: "resources requests for memory"

config:
  __metadata:
    name: "configmap setting"
    label: "configmap setting"
    description: "setting for configmap"
  disable-access-log:
    __metadata:
      name: "access log setting"
      label: "access log setting"
      description: "enable/disable access log, default is disabled"
  ssl-ciphers:
    __metadata:
      name: "ssl ciphers setting"
      label: "ssl ciphers setting"
      description: "set default ssl ciphers suite"


nodeSelector:
  __metadata:
    name: "node selector"
    label: "node selector"
    description: "node selector settings"
  master:
    __metadata:
      name: "node selector"
      label: "node selector"
      description: "select master node"

tolerations:
  __metadata:
    name: "pod tolerations"
    label: "pod tolerations"
    description: "pod tolerations settings"

cert:
  __metadata:
    name: "cert setting"
    label: "cert setting"
    description: "set cert issuer, duration and renewBefore"
  issuer:
    name:
      __metadata:
        name: "cert issuer name setting"
        label: "cert issuer name setting"
        description: "set cert issuer name, default icp-ca-issuer"
    kind:
      __metadata:
        name: "cert issuer kind setting"
        label: "cert issuer kind setting"
        description: "set cert issuer kind, default ClusterIssuer"
  duration:
    __metadata:
      name: "cert duration setting"
      label: "cert duration setting"
      description: "set cert duration, default 2160h"
  renewBefore:
    __metadata:
      name: "cert renewBefore setting"
      label: "cert renewBefore setting"
      description: "set cert duration, default 24h"

## Cluster info
cluster_domain:
  __metadata:
    name: "cluster domain"
    label: "cluster domain"
    description: "cluster domain, for example, cluster.local"
cluster_ca_domain:
  __metadata:
    name: "cluster ca domain"
    label: "cluster ca domain"
    description: "cluster ca domain, for example, mycluster.icp"
oidc_secret:
  __metadata:
    name: "oidc secret"
    label: "oidc secret"
    description: "platform oidc credentials"
cluster_address:
  __metadata:
    name: "cluster address"
    label: "cluster address"
    description: "cluster address ip"
cluster_internal_address:
  __metadata:
    name: "cluster internal address"
    label: "cluster internal address"
    description: "cluster internal address ip"

## Use BYO cert
# tls_secret: icp-management-ingress-tls-secret

## Whether to enable host header check
host_headers_check_enabled:
  __metadata:
    name: "enable host headers check"
    label: "enable host headers check"
    description: "enable/disable host headers check"
allowed_host_headers:
  __metadata:
    name: "allowed host headers"
    label: "allowed host headers"
    description: "allowed host headers list, seperated by space"

## Listening port of nginx backend
httpPort:
  __metadata:
    name: "http port"
    label: "http port"
    description: "Listening port of nginx backend"
httpsPort:
  __metadata:
    name: "https port"
    label: "https port"
    description: "Listening port of nginx backend"

## Use host port
hostPort:
  __metadata:
    name: "hostPort setting"
    label: "hostPort setting"
    description: "use hostPort, default true"

## Use host network
hostNetwork:
  __metadata:
    name: "hostNetwork setting"
    label: "hostNetwork setting"
    description: "hostNetwork setting, default false"

## Whether to enable fips cipher suites
fips_enabled:
  __metadata:
    name: "fips mode setting"
    label: "fips mode setting"
    description: "enable/disable fips mode"

## Whether to do impersonation
enable_impersonation:
  __metadata:
    name: "impersonation setting"
    label: "impersonation setting"
    description: "enable/disable impersonation setting"

## Kubernetes port
apiserver_secure_port:
  __metadata:
    name: "apiserver secure port"
    label: "apiserver secure port"
    description: "kubernetes apiserver secure port"

## Is used internally for externally
internal_use:
  __metadata:
    name: "internal use flag"
    label: "internal use flag"
    description: "is used internally for externally"
